/*
 * [tips]: This file is automatically generated by @mincloudx/cli, please do not modify the file directly.
 */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable no-use-before-define */

export type SchemaId = string | number;

/**
 * Fields ending in "_at" are conventionally designated as timestamp fields.
 **/
export type EpochSeconds = number & { seconds_since_the_unix_start: never };
export type JSONString = string & { json_parsable_string: never };
export type HTMLText = string & { html_content: never };
export type ValueOf<T> = T[keyof T];
export type KeyOf<T> = Array<keyof T>;
export type Default<T = undefined> = T;

export interface BaseTable {
  _id: SchemaId;
  id: SchemaId;
  created_at: number;
  updated_at: number;
  created_by: CreatedBy;
  read_perm: string[];
  write_perm: string[];
}

interface UserProfile extends BaseTable {}

export interface PointerWithoutData {
  id: SchemaId;
  _table: string;
}

export type SchemaPointer<T extends BaseTable> = T | PointerWithoutData;

export type CreatedBy = UserProfile | PointerWithoutData | number;

/**
 * MinCloud File operation result
 */
export interface FileOperationResult {
  /**
   * Record ID
   */
  _id: string;
  /**
   * created time (in Unix timestamp format)
   */
  created_at: number;
  /**
   * Path
   */
  path: string;
  /**
   * created record user ID
   */
  created_by: number;
  /**
   * Mime type
   */
  mime_type: string;
  /**
   * Media type
   */
  media_type: string;
  /**
   * File size
   */
  size: number;
  /**
   * File name
   */
  name: string;
  /**
   * File status
   */
  status: string;
  /**
   * Reference
   */
  reference: string;
  /**
   * CDN path
   */
  cdn_path: string;
  /**
   * Integer. Updated time (in Unix timestamp format)
   */
  updated_at: number;
  /**
   * File categories
   */
  categories: string[];
}

/**
 * 数据表: _userprofile
 * @description
 */
export interface UserProfile extends BaseTable {
  /**
   * 用户昵称
   **/
  nickname: Default | string;
  /**
   * 用户的性别，值为 1 时是男性，值为 2 时是女性，值为 0 时是未知
   **/
  gender: Default | number;
  /**
   * 用户所在国家
   **/
  country: Default | string;
  /**
   * 用户所在省份
   **/
  province: Default | string;
  /**
   * 用户所在城市
   **/
  city: Default | string;
  /**
   * 用户的语言
   **/
  language: Default | string;
  /**
   * openid
   **/
  openid: Default | string;
  /**
   * unionid
   **/
  unionid: Default | string;
  /**
   * 用户头像
   **/
  avatar: Default | string;
  /**
   * 用户是否授权，True 为已授权，False 为未授权
   **/
  is_authorized: Default | boolean;
  /**
   * 用户邮箱是否已经通过验证
   **/
  _email_verified: Default | boolean;
  /**
   * 用户邮箱
   **/
  _email: Default | string;
  /**
   * 用户名
   **/
  _username: Default | string;
  /**
   * 用户在平台方的用户信息
   **/
  _provider: Default | object;
  /**
   * 用户手机
   **/
  _phone: Default | string;
  /**
   * 用户手机是否已经通过验证
   **/
  _phone_verified: Default | boolean;
}

/**
 * 数据表: _richtextcontent
 * @description
 */
export interface RichTextContent extends BaseTable {
  /**
   * 内容的标题
   **/
  title: Default | string;
  /**
   * 内容的简介
   **/
  description: Default | string;
  /**
   * 内容的封面图
   **/
  cover: Default | FileOperationResult;
  /**
   * 内容详情
   **/
  content: Default | string;
  /**
   * 内容库 ID
   **/
  group_id: Default | number;
  /**
   * 内容分类的 ID 列表
   **/
  categories: Default | number[];
  /**
   * 内容阅读数
   **/
  visit_count: Default | number;
}

/**
 * 数据表: channel
 * @description 圈子表
 */
export interface Channel extends BaseTable {
  /**
   * 圈子名称
   **/
  name: Default | string;
  /**
   * 圈子封面图
   **/
  cover: Default | string;
  /**
   * 圈子描述
   **/
  description: Default | string;
  /**
   * 圈子状态
   **/
  status: Default<'approved'> | string | 'approved' | 'deleted';
}

/**
 * 数据表: post
 * @description 帖子
 */
export interface Post extends BaseTable {
  /**
   * 内容
   **/
  content: Default | string;
  /**
   * 封面
   **/
  corver: Default | string;
}
