name: CI
on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: [master]
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: override release tag
  #       required: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Run Tests
        run: pnpm run test
      - name: Build
        run: pnpm run build

  Integration:
    name: TypeScript & Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 18]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Integration Tests
        run: pnpm test -- integration/
